// src/pages/configuracion/providers.js
// Catálogo central de proveedores de IA disponibles

export const PROVIDERS = [
  {
    id: "anthropic",
    nombre: "Claude",
    empresa: "Anthropic",
    iniciales: "An",
    colorBg: "bg-violet-100",
    colorText: "text-violet-700",
    colorBorder: "border-violet-300",
    colorRing: "ring-violet-400",
    badge: "Recomendado",
    badgeColor: "bg-violet-100 text-violet-700",
    descripcion: "Alto rendimiento en tareas de razonamiento y evaluación formativa CNEB.",
    local: false,
    modelos: [
      { id: "claude-sonnet-4-6",          label: "Claude Sonnet 4.6  (Producción)" },
      { id: "claude-opus-4-6",            label: "Claude Opus 4.6    (Alta precisión)" },
      { id: "claude-haiku-4-5-20251001",  label: "Claude Haiku 4.5   (Rápido / económico)" },
    ],
    keyPlaceholder: "sk-ant-api03-••••••••••••••••••••",
    keyHelp: "Obtén tu clave en console.anthropic.com",
    docUrl: "https://docs.anthropic.com",
  },
  {
    id: "openai",
    nombre: "GPT-4o",
    empresa: "OpenAI",
    iniciales: "Oi",
    colorBg: "bg-emerald-100",
    colorText: "text-emerald-700",
    colorBorder: "border-emerald-300",
    colorRing: "ring-emerald-400",
    badge: null,
    badgeColor: "",
    descripcion: "Amplia adopción global. Compatible con formato JSON estructurado.",
    local: false,
    modelos: [
      { id: "gpt-4o",       label: "GPT-4o       (Producción)" },
      { id: "gpt-4o-mini",  label: "GPT-4o Mini  (Económico)" },
      { id: "gpt-4-turbo",  label: "GPT-4 Turbo  (Contexto amplio)" },
    ],
    keyPlaceholder: "sk-proj-••••••••••••••••••••••••••",
    keyHelp: "Obtén tu clave en platform.openai.com",
    docUrl: "https://platform.openai.com/docs",
  },
  {
    id: "google",
    nombre: "Gemini",
    empresa: "Google",
    iniciales: "Gm",
    colorBg: "bg-blue-100",
    colorText: "text-blue-700",
    colorBorder: "border-blue-300",
    colorRing: "ring-blue-400",
    badge: null,
    badgeColor: "",
    descripcion: "Contexto muy largo (1M tokens). Ideal para documentos pedagógicos extensos.",
    local: false,
    modelos: [
      { id: "gemini-1.5-pro",    label: "Gemini 1.5 Pro    (Alta precisión)" },
      { id: "gemini-1.5-flash",  label: "Gemini 1.5 Flash  (Rápido)" },
      { id: "gemini-2.0-flash",  label: "Gemini 2.0 Flash  (Más reciente)" },
    ],
    keyPlaceholder: "AIzaSy••••••••••••••••••••••••••",
    keyHelp: "Obtén tu clave en aistudio.google.com",
    docUrl: "https://ai.google.dev/docs",
  },
  {
    id: "zhipu",
    nombre: "GLM-4",
    empresa: "Zhipu AI",
    iniciales: "Zh",
    colorBg: "bg-orange-100",
    colorText: "text-orange-700",
    colorBorder: "border-orange-300",
    colorRing: "ring-orange-400",
    badge: null,
    badgeColor: "",
    descripcion: "Alternativa asiática competitiva. Buena relación costo-rendimiento.",
    local: false,
    modelos: [
      { id: "glm-4",        label: "GLM-4       (Producción)" },
      { id: "glm-4-flash",  label: "GLM-4 Flash (Económico)" },
      { id: "glm-4-air",    label: "GLM-4 Air   (Balance)" },
    ],
    keyPlaceholder: "••••••••••••••••••••.••••••••••••",
    keyHelp: "Obtén tu clave en open.bigmodel.cn",
    docUrl: "https://open.bigmodel.cn/dev/api",
  },
  {
    id: "mistral",
    nombre: "Mistral",
    empresa: "Mistral AI",
    iniciales: "Mi",
    colorBg: "bg-pink-100",
    colorText: "text-pink-700",
    colorBorder: "border-pink-300",
    colorRing: "ring-pink-400",
    badge: null,
    badgeColor: "",
    descripcion: "Modelo europeo eficiente. Cumple normativas GDPR para datos sensibles.",
    local: false,
    modelos: [
      { id: "mistral-large-latest",    label: "Mistral Large  (Producción)" },
      { id: "mistral-small-latest",    label: "Mistral Small  (Económico)" },
      { id: "open-mixtral-8x22b",      label: "Mixtral 8x22B  (Open-weight)" },
    ],
    keyPlaceholder: "••••••••••••••••••••••••••••••••",
    keyHelp: "Obtén tu clave en console.mistral.ai",
    docUrl: "https://docs.mistral.ai",
  },
  {
    id: "ollama",
    nombre: "Ollama",
    empresa: "Local / Privado",
    iniciales: "Ol",
    colorBg: "bg-purple-100",
    colorText: "text-purple-700",
    colorBorder: "border-purple-300",
    colorRing: "ring-purple-400",
    badge: "Sin costo de API",
    badgeColor: "bg-purple-100 text-purple-700",
    descripcion: "Modelos abiertos en tu propio servidor. Sin enviar datos a terceros.",
    local: true,
    modelos: [
      { id: "llama3.1:8b",   label: "Llama 3.1  8B  (Eficiente)" },
      { id: "llama3.2:3b",   label: "Llama 3.2  3B  (Muy rápido)" },
      { id: "mistral:7b",    label: "Mistral    7B  (Equilibrado)" },
      { id: "qwen2:7b",      label: "Qwen 2     7B  (Multilingüe)" },
    ],
    keyPlaceholder: "(no requiere clave API)",
    keyHelp: "Instala Ollama en tu VPS: curl -fsSL https://ollama.com/install.sh | sh",
    docUrl: "https://ollama.com/docs",
  },
];

export const PROVIDER_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p]));
